# Generated by Django 5.2.3 on 2025-06-15 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_log_app', '0002_entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='title',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
