# Generated by Django 5.2.3 on 2025-06-15 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_log_app', '0003_entry_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='title',
        ),
    ]
