# Generated by Django 5.2.3 on 2025-06-15 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_log_app', '0004_remove_entry_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='title',
            field=models.TextField(null=True),
        ),
    ]
