# Generated by Django 5.2.3 on 2025-06-15 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_log_app', '0007_alter_entry_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='title',
            field=models.CharField(),
        ),
    ]
